name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.5.1.app

    - name: Build and test (unit)
      run: xcodebuild clean build test -project Pokeapi.xcodeproj -scheme "Pokeapi" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro Max" ONLY_ACTIVE_ARCH=YES
